from setuptools import setup
setup(name='lenapy',
version='0.7.1',
description='First release of new lenapy architecture',
url='#',
author='Sebastien Fourest & EMC2 team',
author_email='sebastien.fourest@cnes.fr',
license='APACHE2',
packages=['lenapy','lenapy.utils','lenapy.readers','lenapy.plots'],
install_requires=['matplotlib>=3.8.2','esmpy>=8.4.0','xesmf>=0.8.0','xarray>=2024.2','gsw>=3.6.16','netCDF4>=1.6.5','pyyaml>=6.0','dask>=2023.6'],
zip_safe=False,
entry_points={"xarray.backends": ["lenapyNetcdf = lenapy.readers.geo_reader:lenapyNetcdf",
                                  "lenapyMask   = lenapy.readers.geo_reader:lenapyMask",
                                  "lenapyOceanProducts = lenapy.readers.ocean:lenapyOceanProducts",
                                  "lenapyGfc    = lenapy.readers.produits_gravi:ReadGFC",
                                  "lenapyGraceL2 = lenapy.readers.produits_gravi:ReadGRACEL2"]},
include_package_data=True,
package_data={'lenapy.data': ['*']},
     )
